### ISSUE TITLE
Hard to scroll while inferencing 

### ISSUE THREAD

**Issue by dustinchen93** [nerve-sparks/iris_android#25]
First of all, Thank you for your excellent app🥇!

Story:
Chatting with llama model, I founded it is hard to scroll the screen while the model inferencing.

Environment
stablelm-2-1_6b-chat.Q4_K_M.imx.gguf

Input
"Write a story."

**Comment by Dhruvanand24** [comment]
Working on it, fix coming soon.

**Comment by Dhruvanand24** [comment]
PR #29 solves the issue.
